PATH = 'autos.csv'
TRAIN_COLUMN = {'dateCrawled': str,
    'name': str,
    'seller': str,
    'offerType': str,
    'price': str,
    'abtest': str,
    'vehicleType': str,
    'yearOfRegistration': int,
    'gearbox': str,
    'powerPS': int,
    'model': str,
    'odometer': str,
    'monthOfRegistration': int,
    'fuelType': str,
    'brand': str,
    'notRepairedDamage': str,
    'dateCreated': str,
    'nrOfPictures': int,
    'postalCode': int,
    'lastSeen': str,
 }